services:
  - type: web
    name: mindmate-ai
    runtime: docker
    repo: https://github.com/PuvishaSenthilkumar/Mind-Mate-AI
    plan: free
    region: oregon
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: AI_PROVIDER
        value: mock
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET_KEY
        sync: false